server:
  port: 8002
spring:
  application:
    name: dubbo-customer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: dubbo-provider