server:
  port: 9091
spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  scan:
    base-packages: com.example.service.serviceImpl
  protocols:
    dubbo:
      name: dubbo
      port: 20881
  registry:
    address: spring-cloud://localhost
